 // popis učenika
var sociologijaImena = [
  "Dugo Selo (Zagrebačka)",
"Ivanić-Grad (Zagrebačka)",
"Jastrebarsko (Zagrebačka)",
"Samobor (Zagrebačka)",
"Sveta Nedelja (Zagrebačka)",
"Sveti Ivan Zelina (Zagrebačka)",
"Velika Gorica (Zagrebačka)",
"Vrbovec (Zagrebačka)",
"Zaprešić (Zagrebačka)",
"Donja Stubica (Krapinsko-zagorska)",
"Klanjec (Krapinsko-zagorska)",
"Krapina (Krapinsko-zagorska)",
"Oroslavje (Krapinsko-zagorska)",
"Pregrada (Krapinsko-zagorska)",
"Zabok (Krapinsko-zagorska)",
"Zlatar (Krapinsko-zagorska)",
"Glina (Sisačko-moslavačka)",
"Hrvatska Kostajnica (Sisačko-moslavačka)",
"Kutina (Sisačko-moslavačka)",
"Novska (Sisačko-moslavačka)",
"Petrinja (Sisačko-moslavačka)",
"Popovača (Sisačko-moslavačka)",
"Sisak (Sisačko-moslavačka)",
"Duga Resa (Karlovačka)",
"Karlovac (Karlovačka)",
"Ogulin (Karlovačka)",
"Ozalj (Karlovačka)",
"Slunj (Karlovačka)",
"Gospić (Ličko-senjska)",
"Novalja (Ličko-senjska)",
"Otočac (Ličko-senjska)",
"Senj (Ličko-senjska)",
"Ivanec (Varaždinska)",
"Lepoglava (Varaždinska)",
"Ludbreg (Varaždinska)",
"Novi Marof (Varaždinska)",
"Varaždin (Varaždinska)",
"Varaždinske Toplice (Varaždinska)",
"Đurđevac (Koprivničko-križevačka)",
"Koprivnica (Koprivničko-križevačka)",
"Križevci (Koprivničko-križevačka)",
"Bjelovar (Bjelovarsko-bilogorska)",
"Čazma (Bjelovarsko-bilogorska)",
"Daruvar (Bjelovarsko-bilogorska)",
"Garešnica (Bjelovarsko-bilogorska)",
"Grubišno Polje (Bjelovarsko-bilogorska)",
"Bakar (Primorsko-goranska)",
"Cres (Primorsko-goranska)",
"Crikvenica (Primorsko-goranska)",
"Čabar (Primorsko-goranska)",
"Delnice (Primorsko-goranska)",
"Kastav (Primorsko-goranska)",
"Kraljevica (Primorsko-goranska)",
"Krk (Primorsko-goranska)",
"Mali Lošinj (Primorsko-goranska)",
"Novi Vinodolski (Primorsko-goranska)",
"Opatija (Primorsko-goranska)",
"Rab (Primorsko-goranska)",
"Rijeka (Primorsko-goranska)",
"Vrbovsko (Primorsko-goranska)",
"Orahovica (Virovitičko-podravska)",
"Slatina (Virovitičko-podravska)",
"Virovitica (Virovitičko-podravska)",
"Kutjevo (Požeško-slavonska)",
"Lipik (Požeško-slavonska)",
"Pakrac (Požeško-slavonska)",
"Pleternica (Požeško-slavonska)",
"Požega (Požeško-slavonska)",
"Nova Gradiška (Brodsko-posavska)",
"Slavonski Brod (Brodsko-posavska)",
"Benkovac (Zadarska)",
"Biograd na Moru (Zadarska)",
"Nin (Zadarska)",
"Obrovac (Zadarska)",
"Pag (Zadarska)",
"Zadar (Zadarska)",
"Beli Manastir (Osječko-baranjska)",
"Belišće (Osječko-baranjska)",
"Donji Miholjac (Osječko-baranjska)",
"Đakovo (Osječko-baranjska)",
"Našice (Osječko-baranjska)",
"Osijek (Osječko-baranjska)",
"Valpovo (Osječko-baranjska)",
"Dubrovnik (Dubrovačko-neretvanska)",
"Korčula (Dubrovačko-neretvanska)",
"Metković (Dubrovačko-neretvanska)",
"Opuzen (Dubrovačko-neretvanska)",
"Ploče (Dubrovačko-neretvanska)",
"Drniš (Šibensko-kninska)",
"Knin (Šibensko-kninska)",
"Skradin (Šibensko-kninska)",
"Šibenik (Šibensko-kninska)",
"Vodice (Šibensko-kninska)",
"Ilok (Vukovarsko-srijemska)",
"Otok (Vukovarsko-srijemska)",
"Vinkovci (Vukovarsko-srijemska)",
"Vukovar (Vukovarsko-srijemska)",
"Županja (Vukovarsko-srijemska)",
"Hvar (Splitsko-dalmatinska)",
"Imotski (Splitsko-dalmatinska)",
"Kaštela (Splitsko-dalmatinska)",
"Komiža (Splitsko-dalmatinska)",
"Makarska (Splitsko-dalmatinska)",
"Omiš (Splitsko-dalmatinska)",
"Sinj (Splitsko-dalmatinska)",
"Solin (Splitsko-dalmatinska)",
"Split (Splitsko-dalmatinska)",
"Stari Grad (Splitsko-dalmatinska)",
"Supetar (Splitsko-dalmatinska)",
"Trilj (Splitsko-dalmatinska)",
"Trogir (Splitsko-dalmatinska)",
"Vis (Splitsko-dalmatinska)",
"Vrgorac (Splitsko-dalmatinska)",
"Vrlika (Splitsko-dalmatinska)",
"Buje (Istarska)",
"Buzet (Istarska)",
"Labin (Istarska)",
"Novigrad (Istarska)",
"Pazin (Istarska)",
"Poreč (Istarska)",
"Pula (Istarska)",
"Rovinj (Istarska)",
"Umag (Istarska)",
"Vodnjan (Istarska)",
"Čakovec (Međimurska)",
"Mursko Središće (Međimurska)",
"Prelog (Međimurska)",
"Zagreb (Grad zagreb)"
];
