 // popis učenika
var sociologijaImena = [
  "Berlin - Berlin (glavni grad)",
  "Hamburg - Hamburg",
  "München - Bayern",
  "Köln - Nordrhein-Westfalen",
  "Frankfurt am Main - Hessen",
  "Düsseldorf - Nordrhein-Westfalen",
  "Stuttgart - Baden-Württemberg",
  "Leipzig - Sachsen",
  "Dortmund - Nordrhein-Westfalen",
  "Bremen - Bremen",
  "Essen - Nordrhein-Westfalen",
  "Dresden - Sachsen",
  "Hannover - Niedersachsen",
  "Nürnberg - Bayern",
  "Duisburg - Nordrhein-Westfalen",
  "Bochum - Nordrhein-Westfalen",
  "Wuppertal - Nordrhein-Westfalen",
  "Bielefeld - Nordrhein-Westfalen",
  "Bonn - Nordrhein-Westfalen",
  "Mannheim - Baden-Württemberg",
  "Karlsruhe - Baden-Württemberg",
  "Münster - Nordrhein-Westfalen",
  "Augsburg - Bayern",
  "Wiesbaden - Hessen (glavni grad)",
  "Mönchengladbach - Nordrhein-Westfalen",
  "Gelsenkirchen - Nordrhein-Westfalen",
  "Braunschweig - Niedersachsen",
  "Kiel - Schleswig-Holstein (glavni grad)",
  "Aachen - Nordrhein-Westfalen",
  "Halle (Saale) - Sachsen-Anhalt",
  "Magdeburg - Sachsen-Anhalt (glavni grad)",
  "Erfurt - Thüringen (glavni grad)",
  "Rostock - Mecklenburg-Vorpommern",
  "Mainz - Rheinland-Pfalz (glavni grad)",
  "Kassel - Hessen",
  "Saarbrücken - Saarland (glavni grad)",
  "Freiburg im Breisgau - Baden-Württemberg",
  "Herne - Nordrhein-Westfalen",
  "Osnabrück - Niedersachsen",
  "Oldenburg - Niedersachsen",
  "Paderborn - Nordrhein-Westfalen",
  "Darmstadt - Hessen",
  "Regensburg - Bayern",
  "Ingolstadt - Bayern",
  "Würzburg - Bayern",
  "Fürth - Bayern",
  "Wolfsburg - Niedersachsen",
  "Offenbach am Main - Hessen",
  "Salzgitter - Niedersachsen",
  "Siegen - Nordrhein-Westfalen"
];
