 // popis učenika
var sociologijaImena = [
"New York - New York",
"Los Angeles - California",
"Chicago - Illinois",
"Houston - Texas",
"Phoenix - Arizona (glavni grad)",
"Philadelphia - Pennsylvania",
"San Antonio - Texas",
"San Diego - California",
"Dallas - Texas",
"Fort Worth - Texas",
"Jacksonville - Florida",
"Austin - Texas (glavni grad)",
"San Jose - California",
"Charlotte - North Carolina",
"Columbus - Ohio (glavni grad)",
"Indianapolis - Indiana (glavni grad)",
"San Francisco - California",
"Seattle - Washington",
"Denver - Colorado (glavni grad)",
"Nashville - Tennessee (glavni grad)",
"Oklahoma City - Oklahoma (glavni grad)",
"Washington - District of Columbia",
"El Paso - Texas",
"Las Vegas - Nevada",
"Boston - Massachusetts (glavni grad)",
"Detroit - Michigan",
"Louisville - Kentucky",
"Portland - Oregon",
"Memphis - Tennessee",
"Baltimore - Maryland",
"Milwaukee - Wisconsin",
"Albuquerque - New Mexico",
"Fresno - California",
"Tucson - Arizona",
"Sacramento - California (glavni grad)",
"Atlanta - Georgia (glavni grad)",
"Kansas City - Missouri",
"Mesa - Arizona",
"Raleigh - North Carolina (glavni grad)",
"Colorado Springs - Colorado",
"Miami - Florida",
"Omaha - Nebraska",
"Virginia Beach - Virginia",
"Long Beach - California",
"Oakland - California",
"Minneapolis - Minnesota",
"Bakersfield - California",
"Tulsa - Oklahoma",
"Tampa - Florida",
"Aurora - Colorado",
"Montgomery - Alabama (glavni grad)",
"Juneau - Alaska (glavni grad)",
"Little Rock - Arkansas (glavni grad)",
"Hartford - Connecticut (glavni grad)",
"Dover - Delaware (glavni grad)",
"Tallahassee - Florida (glavni grad)",
"Honolulu - Hawaii (glavni grad)",
"Boise - Idaho (glavni grad)",
"Springfield - Illinois (glavni grad)",
"Des Moines - Iowa (glavni grad)",
"Topeka - Kansas (glavni grad)",
"Frankfort - Kentucky (glavni grad)",
"Baton Rouge - Louisiana (glavni grad)",
"Augusta - Maine (glavni grad)",
"Annapolis - Maryland (glavni grad)",
"Lansing - Michigan (glavni grad)",
"St. Paul - Minnesota (glavni grad)",
"Jackson - Mississippi (glavni grad)",
"Jefferson City - Missouri (glavni grad)",
"Helena - Montana (glavni grad)",
"Lincoln - Nebraska (glavni grad)",
"Carson City - Nevada (glavni grad)",
"Concord - New Hampshire (glavni grad)",
"Trenton - New Jersey (glavni grad)",
"Santa Fe - New Mexico (glavni grad)",
"Albany - New York (glavni grad)",
"Bismarck - North Dakota (glavni grad)",
"Salem - Oregon (glavni grad)",
"Harrisburg - Pennsylvania (glavni grad)",
"Providence - Rhode Island (glavni grad)",
"Columbia - South Carolina (glavni grad)",
"Pierre - South Dakota (glavni grad)",
"Salt Lake City - Utah (glavni grad)",
"Montpelier - Vermont (glavni grad)",
"Richmond - Virginia (glavni grad)",
"Olympia - Washington (glavni grad)",
"Charleston - West Virginia (glavni grad)",
"Madison - Wisconsin (glavni grad)",
"Cheyenne - Wyoming (glavni grad)",
"Arlington - Texas",
"New Orleans - Louisiana",
"Wichita - Kansas",
"Cleveland - Ohio",
"Stockton - California",
"Cincinnati - Ohio",
"St. Louis - Missouri",
"Orlando - Florida",
"Pittsburgh - Pennsylvania",
"Plano - Texas",
"Durham - North Carolina"
];
